### PR TITLE
fix crashing of network on invalid numbering

### LINKED ISSUE #320: Error: pre-condition: previousNumber < number
Sentry Issue: [NETWORK-10](https://sentry.io/organizations/streamr/issues/1143963299/?referrer=github_integration)

```
Error: pre-condition: previousNumber < number
  ?, in Array.forEach
...
(5 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by harbu**
Fixes #320 

Don't crash node in the presence of a message with invalid numbering. Instead emit a `debug` message and increment metrics counter of error type.

### CODE REVIEW

File: src/logic/DuplicateMessageDetector.js [hunk 1]
```diff
@@ -83,7 +91,7 @@ class DuplicateMessageDetector {
      */
     markAndCheck(previousNumber, number) {
         if (previousNumber && previousNumber.greaterThanOrEqual(number)) {
-            throw new Error('pre-condition: previousNumber < number')
+            throw new InvalidNumberingError()
```
Comment (mirpo) [inline src/logic/DuplicateMessageDetector.js:94]: 👍

**Review by mirpo — APPROVED** [review]
